"""empty message

Revision ID: 125aa5132db4
Revises: 73d706c26863
Create Date: 2023-11-12 13:31:04.833097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125aa5132db4'
down_revision = '73d706c26863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_shows', sa.ARRAY(sa.String(length=500)), nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows', sa.ARRAY(sa.String(length=500)), nullable=True))
        batch_op.add_column(sa.Column('past_shows_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('looking_for_talent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('looking_for_talent')
        batch_op.drop_column('upcoming_shows_count')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('past_shows')

    # ### end Alembic commands ###
