"""empty message

Revision ID: 330dbb83da01
Revises: 684498f9eede
Create Date: 2023-11-19 19:10:44.585851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '330dbb83da01'
down_revision = '684498f9eede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))
        batch_op.drop_column('past_shows')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('upcoming_shows_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows', postgresql.ARRAY(sa.VARCHAR(length=500)), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('past_shows', postgresql.ARRAY(sa.VARCHAR(length=500)), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_description')

    # ### end Alembic commands ###
