"""empty message

Revision ID: 73d706c26863
Revises: ad9fe491e163
Create Date: 2023-11-07 21:29:11.199730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d706c26863'
down_revision = 'ad9fe491e163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('past_shows', sa.ARRAY(sa.String(length=500)), nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows', sa.ARRAY(sa.String(length=500)), nullable=True))
        batch_op.add_column(sa.Column('past_shows_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_talent')
        batch_op.drop_column('website')
        batch_op.drop_column('genres')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('upcoming_shows_count')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('past_shows')
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
