"""empty message

Revision ID: 763820aef47a
Revises: 330dbb83da01
Create Date: 2023-11-19 20:26:45.441200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763820aef47a'
down_revision = '330dbb83da01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_shows', sa.ARRAY(sa.String(length=500)), nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows', sa.ARRAY(sa.String(length=500)), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('past_shows')

    # ### end Alembic commands ###
