"""empty message

Revision ID: 9142581104bd
Revises: 86a80aec550c
Create Date: 2023-11-21 19:08:43.129506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9142581104bd'
down_revision = '86a80aec550c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('shows')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('shows')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shows', postgresql.ARRAY(sa.VARCHAR(length=500)), autoincrement=False, nullable=True))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shows', postgresql.ARRAY(sa.VARCHAR(length=500)), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
