"""empty message

Revision ID: addb10af3dbc
Revises: 125aa5132db4
Create Date: 2023-11-12 14:13:43.023308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addb10af3dbc'
down_revision = '125aa5132db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('looking_for_talent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
